# Generated by Django 4.2.5 on 2023-10-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='document', verbose_name='Загрузить документ')),
            ],
        ),
        migrations.CreateModel(
            name='Remains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('article', models.CharField(max_length=50, null=True)),
                ('party', models.CharField(max_length=9, null=True)),
                ('title', models.TextField(null=True)),
                ('base_unit', models.CharField(max_length=10, null=True)),
                ('project', models.CharField(max_length=30, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
    ]
