# Generated by Django 4.2.5 on 2023-10-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='enterprise/doc/base', verbose_name='Выберите файл')),
            ],
        ),
        migrations.CreateModel(
            name='Remains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('article', models.CharField(max_length=30)),
                ('party', models.CharField(max_length=9)),
                ('title', models.CharField(max_length=100)),
                ('base_unit', models.CharField(max_length=10)),
                ('project', models.CharField(max_length=20)),
                ('quantity', models.FloatField(blank=True)),
            ],
        ),
    ]
