# Generated by Django 4.2.5 on 2023-10-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remains',
            name='article',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='remains',
            name='base_unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='remains',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='remains',
            name='comment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='remains',
            name='party',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='remains',
            name='project',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='remains',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remains',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
