# Generated by Django 4.2.5 on 2023-11-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinventory',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderinventory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
