# Generated by Django 4.2.5 on 2023-11-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_orderinventory_address_orderinventory_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinventory',
            old_name='address',
            new_name='addres',
        ),
    ]
