# Generated by Django 4.2.5 on 2023-11-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_rename_address_orderinventory_addres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinventory',
            old_name='addres',
            new_name='address',
        ),
    ]
