# Generated by Django 4.2.5 on 2023-11-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_rename_addres_orderinventory_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainsinventory',
            name='status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
